---
url: "http://localhost:8080"
database:
  host: "localhost"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
users:
  cat_manager:
    email: "henrique@henrique.com"
    pass: "123456"
  admin:
    email: "admin@admin.com"
    pass: "123456"
